// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movements.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movements.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250522010005_ExternalIdentifierChanged")]
    partial class ExternalIdentifierChanged
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Movements.Domain.TrainOperations.TrainOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.ComplexProperty<Dictionary<string, object>>("RailwaySectionFromIdentifier", "Movements.Domain.TrainOperations.TrainOperation.RailwaySectionFromIdentifier#ExternalIdentifier", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("railway_section_from_identifier_value");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("RailwaySectionToIdentifier", "Movements.Domain.TrainOperations.TrainOperation.RailwaySectionToIdentifier#ExternalIdentifier", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("railway_section_to_identifier_value");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TrainIdentifier", "Movements.Domain.TrainOperations.TrainOperation.TrainIdentifier#ExternalIdentifier", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("train_identifier_value");
                        });

                    b.HasKey("Id")
                        .HasName("pk_train_operations");

                    b.ToTable("train_operations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
